package smartbuy.buyerprofile;

import jakarta.persistence.*;

import lombok.Getter;
import lombok.Setter;
import smartbuy.PriorityMode;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Entity class representing a user's buying preferences.
 * Since the application uses a "Guest Mode" (no login), this profile
 * is linked to a unique session ID rather than a user account.
 */
@Entity
@Table(name="buyer_profiles")
@Getter
public class BuyerProfile {

    // Primary Key: Internal ID for the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long profileId;

    /**
     * The unique identifier for the guest user (e.g., UUID generated by frontend).
     * This acts as the "username" for the current session.
     * Must be unique to ensure one profile per session.
     */
    @Column(nullable = false, unique = true)
    @Setter
    private String sessionId;

    // --- Financial Constraints ---
    @Column(nullable = false)
    @Setter
    private BigDecimal maxPrice;

    // --- Space Requirements ---
    @Column(nullable = false)
    @Setter
    private Integer minBedrooms;

    @Column(nullable = false)
    @Setter
    private BigDecimal minBathrooms;

    /**
     * The scoring strategy selected by the user.
     * Determines how much weight is assigned to Price, Space, Safety, and Schools.
     * Stored as a String in the database (e.g., "BUDGET_DRIVEN").
     */
    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    @Setter
    private PriorityMode priorityMode;

    // Audit field: Tracks when the profile was last modified
    private LocalDateTime updatedAt;

    // Constructors
    public BuyerProfile() {}

    // Lifecycle Hook: Automatically updates the timestamp before saving.
    @PrePersist
    @PreUpdate
    public void setupTimestamp() {
        this.updatedAt = LocalDateTime.now();
    }

    public double[] getWeights() {
        return priorityMode != null ? priorityMode.getWeights() : null;
    }
}
