package smartbuy.buyerProfile;

import jakarta.persistence.*;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * Entity class representing a user's buying preferences.
 * Since the application uses a "Guest Mode" (no login), this profile
 * is linked to a unique session ID rather than a user account.
 */
@Entity
@Table(name="buyer_profiles")
@Getter
public class BuyerProfile {

    // Primary Key: Internal ID for the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long profileId;

    /**
     * The unique identifier for the guest user (e.g., UUID generated by frontend).
     * This acts as the "username" for the current session.
     * Must be unique to ensure one profile per session.
     */
    @Column(nullable = false, unique = true)
    @Setter
    private String sessionId;

    // --- Financial Constraints ---
    @Column(nullable = false)
    @NotNull(message = "Price can not be empty")
    @DecimalMin(value = "0.0", inclusive = true, message = "Price can not be negative")
    @Setter
    private Double maxPrice;

    // --- Space Requirements ---
    @Column(nullable = false)
    @NotNull(message = "Bedrooms can not be null")
    @Min(value = 0, message = "Number of bedrooms can not be negative")
    @Setter
    private Integer minBedrooms;

    @Column(nullable = false)
    @NotNull(message = "bathrooms can not be null")
    @Min(value = 0, message = "Number of bathrooms can not be negative")
    @Setter
    private Integer minBathrooms;

    /**
     * The scoring strategy selected by the user.
     * Determines how much weight is assigned to Price, Space, Safety, and Schools.
     * Stored as a String in the database (e.g., "BUDGET_DRIVEN").
     */
    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    @Setter
    private PriorityMode priorityMode;

    public enum PriorityMode {
        BALANCED,
        BUDGET_DRIVEN,
        SAFETY_FIRST,
        EDUCATION_FIRST
    }

    // Audit field: Tracks when the profile was last modified
    private LocalDateTime updatedAt;

    // Constructors
    public BuyerProfile() {}

    // Lifecycle Hook: Automatically updates the timestamp before saving.
    @PrePersist
    @PreUpdate
    public void setupTimestamp() {
        this.updatedAt = LocalDateTime.now();
    }

    public double[] getWeights() {
        return switch (priorityMode) {
            case BALANCED -> new double[]{0.25, 0.25, 0.25, 0.25};
            case BUDGET_DRIVEN -> new double[]{0.50, 0.20, 0.20, 0.10};
            case SAFETY_FIRST -> new double[]{0.25, 0.15, 0.50, 0.10};
            case EDUCATION_FIRST -> new double[]{0.20, 0.15, 0.15, 0.50};
        };
    }
}
